// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb4xUnmYaA83je6fY4cPrngnhulgcRvrE',
    appId: '1:1085412120207:web:your_web_app_id',
    messagingSenderId: '1085412120207',
    projectId: 'discover-melaka-event',
    authDomain: 'discover-melaka-event.firebaseapp.com',
    storageBucket: 'discover-melaka-event.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb4xUnmYaA83je6fY4cPrngnhulgcRvrE',
    appId: '1:1085412120207:android:ad02cc8218429e670c82fa',
    messagingSenderId: '1085412120207',
    projectId: 'discover-melaka-event',
    storageBucket: 'discover-melaka-event.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb4xUnmYaA83je6fY4cPrngnhulgcRvrE',
    appId: '1:1085412120207:ios:your_ios_app_id',
    messagingSenderId: '1085412120207',
    projectId: 'discover-melaka-event',
    storageBucket: 'discover-melaka-event.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb4xUnmYaA83je6fY4cPrngnhulgcRvrE',
    appId: '1:1085412120207:ios:your_ios_app_id',
    messagingSenderId: '1085412120207',
    projectId: 'discover-melaka-event',
    storageBucket: 'discover-melaka-event.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}